spring:
  profiles:
    active: DEV
  cloud:
    config:
      uri: http://localhost:8888
  application:
    name: edge-one
  #webflux:
    #base-path: /${spring.application.name}

server:
  port: 0

#eureka:
  #client:
    #serviceUrl:
      #defaultZone: http://localhost:8083/eureka
