server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/

spring:
  # Spring properties in case you use different profiles
  profiles:
    active: DEV
  application:
    name: config-server
  # Spring Cloud Config Server Repository
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          default-label: main
          uri: https://github.com/srhojo/fenix-arq-cloud-config.git
          search-paths:
            - DEV